// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240204144529_AlimentarTablaVilla")]
    partial class AlimentarTablaVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaDeActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenida = "",
                            Detalle = "Detalle de la villa..",
                            FechaDeActualizacion = new DateTime(2024, 2, 4, 11, 45, 29, 823, DateTimeKind.Local).AddTicks(3255),
                            FechaDeCreacion = new DateTime(2024, 2, 4, 11, 45, 29, 823, DateTimeKind.Local).AddTicks(3207),
                            ImageUrl = "",
                            MetrosCuadrados = 150,
                            Nombre = "Villa nancy",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenida = "",
                            Detalle = "Detalle de la villa..",
                            FechaDeActualizacion = new DateTime(2024, 2, 4, 11, 45, 29, 823, DateTimeKind.Local).AddTicks(3289),
                            FechaDeCreacion = new DateTime(2024, 2, 4, 11, 45, 29, 823, DateTimeKind.Local).AddTicks(3287),
                            ImageUrl = "",
                            MetrosCuadrados = 40,
                            Nombre = "Premiun a la Piscina",
                            Ocupantes = 2,
                            Tarifa = 270.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
